Update nexus-upload-latest

diff --git a/nexus-upload-latest b/nexus-upload-latest
--- a/nexus-upload-latest
+++ b/nexus-upload-latest
@@ -7,39 +7,118 @@
 # Usage   : nexus_upload.sh <RSTATE> </PATH/FILE_NAME>
 # ********************************************************************
 
+
+#####################################################################################################
+##                  DECLARING VARIABLES START                                                  ##
+#####################################################################################################
+
 M2_HOME=~/.m2
 MVN_PATH=/usr/bin/mvn
 USER_NAME=nmiteam
 NEXUS_URL=https://arm104-eiffel004.lmera.ericsson.se:8443/nexus/content/repositories/assure-releases/
 NEXUS_REPO_ID=assure-releases
-ARTIFACT_GROUP_ID=com.ericsson.eniq.stats.nmi
-ARTIFACT_VERSION=$1
-LOGPATH=/tmp/nexus_upload_log/$0_log
-LOG_FILE=$LOGPATH/$(date +%F).$ARTIFACT_ID.log
-LINK_PATH=com/ericsson/eniq/stats/nmi/$2
+ARTIFACT_VERSION=$2
+SHIPMENT=$1
+SCRIPT_NAME=$(basename $0)
+SCRIPT_NAME="${SCRIPT_NAME%.*}"
+ARTIFACT_GROUP_ID=com.ericsson.eniq.stats.nmi.${SHIPMENT//./_}
+LOGPATH=/tmp/${SCRIPT_NAME}_log
+LOG_FILE=$LOGPATH/$(date +%F).log
+LINK_PATH=com/ericsson/eniq/stats/nmi/${SHIPMENT//./_}
 UEP={5D3lAgKYiHgHcZ51FFhETCFvPlIatXrcRHHGkHPYHA8=}
 MEP={3g2ExFC9KWYH8iAXowQZQOdUBL7loY90Zz4ROmh9Zhw=}
 
-logger -t INFO $0 script started to upload $FILE_NAME to nexus
+[ ! -d $LOGPATH ] &&  mkdir $LOGPATH
+
+#####################################################################################################
+##                  DECLARING VARIABLES END                                                  ##
+#####################################################################################################
+
+#####################################################################################################
+#                            DECLARING  LOGGER FUNCTIONS START                                     ##
+#####################################################################################################
+
+SCRIPTENTRY(){
+  timeAndDate=`date`
+  script_name=`basename "$0"`
+  script_name="${script_name%.*}"
+  echo "[$timeAndDate] [DEBUG]  : $script_name $FUNCNAME" >> $LOG_FILE
+}
+
+ENTRY(){
+  local cfn="${FUNCNAME[1]}"
+  timeAndDate=`date`
+  echo "[$timeAndDate] [DEBUG]  : $cfn $FUNCNAME" >> $LOG_FILE
+}
+
+INFO(){
+  local msg="$1"
+  timeAndDate=`date`
+  echo "[$timeAndDate] [INFO]   : $msg" |& tee -a $LOG_FILE
+}
+
+DEBUG(){
+  local msg="$1"
+  timeAndDate=`date`
+  echo "[$timeAndDate] [DEBUG]  : $msg" >> $LOG_FILE
+}
+
+
+SUCCESS(){
+  local function_name="${FUNCNAME[1]}"
+  local msg="$1"
+  timeAndDate=`date`
+  echo "[$timeAndDate] [SUCCESS]  : $msg" | tee -a  $LOG_FILE
+}
+
+ERROR(){
+  local function_name="${FUNCNAME[1]}"
+  local msg="$1"
+  timeAndDate=`date`
+  echo "[$timeAndDate] [ERROR]  : $msg" | tee -a  $LOG_FILE
+}
+
+EXIT(){
+  local cfn="${FUNCNAME[1]}"
+  timeAndDate=`date`
+  echo "[$timeAndDate] [DEBUG]  : $cfn $FUNCNAME" >> $LOG_FILE
+}
+
+SCRIPTEXIT(){
+  echo "[$timeAndDate] [DEBUG]  : $script_name $FUNCNAME" >> $LOG_FILE
+}
+
+
+#####################################################################################################
+##                  DECLARING LOGGER FUNCTION END                                                  ##
+#####################################################################################################
+
+SCRIPTENTRY
 
 # ********************************************************************
 #Validating arguments/inputs &  exit with Usage message
 #else it will create dir. to save log and copy checksum of file to log file
 #  ********************************************************************
 
-if [[ $# -ne 3 || ! -f $3 ]] ;
+if [[ $# -ne 3 || ! -f $3 || $ARTIFACT_VERSION != R* ]] ;
   then
-    logger -st INFO "Usage: $0 RSTATE SHIPMENT /PATH/FILE_NAME"
-    logger -t EXIT $0 script exited with Usage message
+    INFO "Usage: $0 SHIPMENT RSTATE /PATH/FILE_NAME"
+    DEBUG "script exited with Usage message"
+    SCRIPTEXIT
     exit 100
   else
+    ENTRY
     FILE_NAME=$(basename $3)
     ARTIFACT_ID=${FILE_NAME%%.*}
-    LOG_FILE=$LOGPATH/$(date +%F).$ARTIFACT_ID.log
     CHECKSUM_LOG_FILE=$LOGPATH/$(date +%F).$ARTIFACT_ID.checksum
-    mkdir -p $LOGPATH
     md5sum $FILE_NAME > $CHECKSUM_LOG_FILE
 fi
+
+DEBUG "checksum calulated for $ARTIFACT_ID file"
+
+#####################################################################################################
+##                  DECLARING SCRIPT FUNCTION START                                                  ##
+#####################################################################################################
 
 ### Function: insert_before_servers ###
 #
@@ -50,9 +129,9 @@ fi
 #
 
 insert_before_servers () {
-logger -t INFO $USER_NAME not found in $M2_HOME/settings.xml file
+DEBUG "$USER_NAME not found in $M2_HOME/settings.xml file"
 sed -i "/<servers>/a     <server>\n    <id>assure-releases<\/id>\n    <username>$USER_NAME<\/username>\n    <password>$UEP<\/password>\n<\/server>" $M2_HOME/settings.xml
-logger -t INFO $USER_NAME added to $M2_HOME/settings.xml file
+DEBUG "$USER_NAME added to $M2_HOME/settings.xml file"
 }
 
 ### Function: insert_before_settings ###
@@ -64,9 +143,9 @@ logger -t INFO $USER_NAME added to $M2_HOME/settings.xml file
 #
 
 insert_before_settings () {
-logger -t INFO $USER_NAME not found in $M2_HOME/settings.xml file
+DEBUG "$USER_NAME not found in $M2_HOME/settings.xml file"
 sed -i "/<\/settings>/i   <servers>\n  <server>\n    <id>assure-releases<\/id>\n    <username>$USER_NAME<\/username>\n    <password>$UEP<\/password>\n  <\/server>\n<\/servers>" $M2_HOME/settings.xml
-logger -t INFO $USER_NAME added to $M2_HOME/settings.xml file
+DEBUG "$USER_NAME added to $M2_HOME/settings.xml file"
 }
 
 ### Function: setting_security_file ###
@@ -78,13 +157,12 @@ logger -t INFO $USER_NAME added to $M2_HOME/settings.xml file
 #
 
 setting_security_file () {
-logger -t INFO $M2_HOME/settings-security.xml file  not found
 cat <<EOF > $M2_HOME/settings-security.xml
 <settingsSecurity>
   <master>${MEP}</master>
 </settingsSecurity>
 EOF
-logger -t INFO $M2_HOME/settings-security.xml file created
+DEBUG "$M2_HOME/settings-security.xml file created"
 }
 
 ### Function: setting_file ###
@@ -96,7 +174,7 @@ logger -t INFO $M2_HOME/settings-security.xml file created
 #
 
 setting_file () {
-logger -t INFO $M2_HOME/settings.xml file  not found
+DEBUG "$M2_HOME/settings.xml file  not found"
 cat <<EOF > $M2_HOME/settings.xml
 <?xml version="1.0"?>
 <settings>
@@ -109,7 +187,7 @@ cat <<EOF > $M2_HOME/settings.xml
   </servers>
 </settings>
 EOF
-logger -t INFO $M2_HOME/settings.xml file created
+DEBUG "$M2_HOME/settings.xml file created"
 }
 
 ### Function: success ###
@@ -121,10 +199,12 @@ logger -t INFO $M2_HOME/settings.xml file created
 #
 
 success () {
-logger -st INFO  CHECKSUM OF $FILE_NAME IS `awk '{print $1}' $CHECKSUM_LOG_FILE` and saved in $CHECKSUM_LOG_FILE
+INFO  "CHECKSUM OF $FILE_NAME IS `awk '{print $1}' $CHECKSUM_LOG_FILE` and saved in $CHECKSUM_LOG_FILE"
 sleep 2s
-logger -st SUCCESS $FILE_NAME is successfully uploaded by $USER_NAME and nexus link is $NEXUS_URL$LINK_PATH/$ARTIFACT_ID/$ARTIFACT_VERSION/
-logger  -st INFO you can check maven_log from $LOG_FILE
+SUCCESS "$FILE_NAME is successfully uploaded by $USER_NAME and nexus link is $NEXUS_URL$LINK_PATH/$ARTIFACT_ID/$ARTIFACT_VERSION/"
+INFO "you can check maven_log from $LOG_FILE"
+EXIT
+SCRIPTEXIT
 }
 
 ### Function: unsuccess ###
@@ -136,7 +216,9 @@ logger  -st INFO you can check maven_log from $LOG_FILE
 #
 
 unsuccess () {
-logger -st ERROR $FILE_NAME is Failed to upload and please check the log from $LOG_FILE and try again
+ERROR "$FILE_NAME is Failed to upload and please check the log from $LOG_FILE and try again"
+EXIT
+SCRIPTEXIT
 }
 
 ### Function: maven_cmd ###
@@ -148,9 +230,23 @@ logger -st ERROR $FILE_NAME is Failed to upload and please check the log from $L
 #
 
 maven_cmd () {
-logger -st INFO $FILE_NAME is uploading...
-$MVN_PATH -B deploy:deploy-file -Durl=$NEXUS_URL -DrepositoryId=$NEXUS_REPO_ID -DgroupId=$ARTIFACT_GROUP_ID -Dversion=$ARTIFACT_VERSION -DartifactId=$ARTIFACT_ID  -Dfile=$FILE_NAME >> $LOG_FILE
+$MVN_PATH -version &>> $LOG_FILE
+if [ $? = 0 ] ;
+  then
+    INFO "$FILE_NAME is uploading..."
+    $MVN_PATH -B deploy:deploy-file -Durl=$NEXUS_URL -DrepositoryId=$NEXUS_REPO_ID -DgroupId=$ARTIFACT_GROUP_ID -Dversion=$ARTIFACT_VERSION -DartifactId=$ARTIFACT_ID  -Dfile=$FILE_NAME >> $LOG_FILE
+  else
+   ERROR "Please set environment variable for maven path to $MVN_PATH"
+   EXIT
+   SCRIPTEXIT
+   exit 401
+fi
 }
+
+
+#####################################################################################################
+##                  DECLARING SCRIP FUNCTION END                                                  ##
+#####################################################################################################
 
 #Excution: If 2 files or not exist then it will create and upload artifact to nexus and maven log will save to $LOGPATH
 if [[ ! -f $M2_HOME/settings.xml || ! -f $M2_HOME/settings-security.xml ]];
@@ -214,4 +310,3 @@ if [[ ! -f $M2_HOME/settings.xml || ! -f $M2_HOME/settings-security.xml ]];
         fi
 fi
 #END
-
